### ISSUE TITLE
Potted Flowers Have Extra Terracotta Pot

### ISSUE THREAD

**Issue by LazyJ** [VanessaE/hdx-512#4]
Howdy ;)

The potted flowers textures, in the HDX series, still have the terracotta pot in them so when potted flowers are placed, there are two flower pots shown; the smaller flower pot stacked on top the new meshnode pot.

Thanks for maintaining HDX ;)

**Comment by VanessaE** [comment]
Fixed with latest commits to HDX and Home Decor.
